# Generated by Django 6.0.5 on 2026-05-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("stock", models.PositiveIntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
